server:
  port: 7901
  # context-path: /test
spring:
  application:
    name: springcloud-demo-micoservice-test
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    # home-page-url: /test   配合server.context-path使用
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.example.demo.feign.UserFeignClient : DEBUG